/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-21 12:01:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1569048512295L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1568915186021L));
    _jspx_dependants.put("/views/common/calendar.jsp", Long.valueOf(1569067006190L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<title>Quixlab - Bootstrap Admin Dashboard Template by\r\n");
      out.write("\tThemefisher.com</title>\r\n");
      out.write("<!-- Favicon icon -->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n");
      out.write("\thref=\"./resources/logo1.png\">\r\n");
      out.write("<!-- Custom Stylesheet -->\r\n");
      out.write("<link href=\"views/common/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--*******************\r\n");
      out.write("        Preloader start\r\n");
      out.write("    ********************-->\r\n");
      out.write("\t<div id=\"preloader\">\r\n");
      out.write("\t\t<div class=\"loader\">\r\n");
      out.write("\t\t\t<svg class=\"circular\" viewBox=\"25 25 50 50\"> <circle class=\"path\" cx=\"50\" cy=\"50\" r=\"20\" fill=\"none\" stroke-width=\"3\"\r\n");
      out.write("\t\t\t\tstroke-miterlimit=\"10\" /> </svg>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--*******************\r\n");
      out.write("        Preloader end\r\n");
      out.write("    ********************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--**********************************\r\n");
      out.write("        Main wrapper start\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("\t<div id=\"main-wrapper\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/ee2dc8e60a.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Stylesheet -->\r\n");
      out.write("    <link href=\"views/common/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  <!--**********************************\r\n");
      out.write("            Nav header start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"nav-header\">\r\n");
      out.write("            <div class=\"brand-logo\" style=\"background:white;\">\r\n");
      out.write("                <a href=\"index.html\">\r\n");
      out.write("                    <b class=\"logo-abbr\"><img src=\"resources/logo1.png\" alt=\"\"> </b>\r\n");
      out.write("                    <span class=\"logo-compact\"><img src=\"resources/logo1.png\" alt=\"\"></span>\r\n");
      out.write("                    <span class=\"brand-title\">\r\n");
      out.write("                        <img src=\"resources/logo2.png\" alt=\"\">\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Nav header end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Header start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"header\">    \r\n");
      out.write("            <div class=\"header-content clearfix\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"nav-control\">\r\n");
      out.write("                    <div class=\"hamburger\">\r\n");
      out.write("                        <span class=\"toggle-icon\"><i class=\"icon-menu\"></i></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-left\">\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-right\">\r\n");
      out.write("                    <ul class=\"clearfix\">\r\n");
      out.write("                        <li class=\"icons dropdown\"><a href=\"javascript:void(0)\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"mdi mdi-email-outline\"></i>\r\n");
      out.write("                                <span class=\"badge gradient-1 badge-pill badge-primary\">3</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"drop-down animated fadeIn dropdown-menu\">\r\n");
      out.write("                                <div class=\"dropdown-content-heading d-flex justify-content-between\">\r\n");
      out.write("                                    <span class=\"\">3 New Messages</span>  \r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-content-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li class=\"notification-unread\">\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"views/common/images/avatar/1.jpg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <div class=\"notification-heading\">Saiful Islam</div>\r\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("                                                    <div class=\"notification-text\">Hi Teddy, Just wanted to let you ...</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"notification-unread\">\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"views/common/images/avatar/2.jpg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <div class=\"notification-heading\">Adam Smith</div>\r\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("                                                    <div class=\"notification-text\">Can you do me a favour?</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"views/common/images/avatar/3.jpg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <div class=\"notification-heading\">Barak Obama</div>\r\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("                                                    <div class=\"notification-text\">Hi Teddy, Just wanted to let you ...</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"views/common/images/avatar/4.jpg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <div class=\"notification-heading\">Hilari Clinton</div>\r\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("                                                    <div class=\"notification-text\">Hello</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"icons dropdown\"><a href=\"javascript:void(0)\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"mdi mdi-bell-outline\"></i>\r\n");
      out.write("                                <span class=\"badge badge-pill gradient-2 badge-primary\">3</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"drop-down animated fadeIn dropdown-menu dropdown-notfication\">\r\n");
      out.write("                                <div class=\"dropdown-content-heading d-flex justify-content-between\">\r\n");
      out.write("                                    <span class=\"\">2 New Notifications</span>  \r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-content-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-success-lighten-2\"><i class=\"icon-present\"></i></span>\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <h6 class=\"notification-heading\">Events near you</h6>\r\n");
      out.write("                                                    <span class=\"notification-text\">Within next 5 days</span> \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-danger-lighten-2\"><i class=\"icon-present\"></i></span>\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <h6 class=\"notification-heading\">Event Started</h6>\r\n");
      out.write("                                                    <span class=\"notification-text\">One hour ago</span> \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-success-lighten-2\"><i class=\"icon-present\"></i></span>\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <h6 class=\"notification-heading\">Event Ended Successfully</h6>\r\n");
      out.write("                                                    <span class=\"notification-text\">One hour ago</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-danger-lighten-2\"><i class=\"icon-present\"></i></span>\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <h6 class=\"notification-heading\">Events to Join</h6>\r\n");
      out.write("                                                    <span class=\"notification-text\">After two days</span> \r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"icons dropdown d-none d-md-flex\">\r\n");
      out.write("                            <a href=\"javascript:void(0)\" class=\"log-user\"  data-toggle=\"dropdown\">\r\n");
      out.write("                                <span>English</span>  <i class=\"fa fa-angle-down f-s-14\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"drop-down dropdown-language animated fadeIn  dropdown-menu\">\r\n");
      out.write("                                <div class=\"dropdown-content-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"javascript:void()\">English</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void()\">Dutch</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"icons dropdown\">\r\n");
      out.write("                            <div class=\"user-img c-pointer position-relative\"   data-toggle=\"dropdown\">\r\n");
      out.write("                                <span class=\"activity active\"></span>\r\n");
      out.write("                                <img src=\"views/common/images/user/1.png\" height=\"40\" width=\"40\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"drop-down dropdown-profile   dropdown-menu\">\r\n");
      out.write("                                <div class=\"dropdown-content-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"app-profile.html\"><i class=\"icon-user\"></i> <span>Profile</span></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"email-inbox.html\"><i class=\"icon-envelope-open\"></i> <span>Inbox</span> <div class=\"badge gradient-3 badge-pill badge-primary\">3</div></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <hr class=\"my-2\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"page-lock.html\"><i class=\"icon-lock\"></i> <span>Lock Screen</span></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li><a href=\"page-login.html\"><i class=\"icon-key\"></i> <span>Logout</span></a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Header end ti-comment-alt\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Sidebar start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"nk-sidebar\">           \r\n");
      out.write("            <div class=\"nk-nav-scroll\">\r\n");
      out.write("                <ul class=\"metismenu\" id=\"menu\">\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"widgets.html\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"far fa-check-square\"></i><span class=\"nav-text\">공지사항</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"mega-menu mega-menu-sm\">\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"fas fa-file-signature\"></i><span class=\"nav-text\">전자결재</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("\r\n");
      out.write("                            <li><a href=\"./layout-blank.html\">-전체 목록</a></li>\r\n");
      out.write("                            <li><a href=\"./layout-one-column.html\">-결재요청문서</a></li>\r\n");
      out.write("                            <li><a href=\"./layout-two-column.html\">-결재문서 등록</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>   \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"fas fa-calculator\"></i><span class=\"nav-text\">총무/회계</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("                            <li><a href=\"./app-profile.html\">-공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"./app-profile.html\">-매출관리</a></li>\r\n");
      out.write("                            <li><a href=\"./app-calender.html\">-O/S관리</a></li>\r\n");
      out.write("                            <li><a href=\"./app-calender.html\">-사내물품 관리</a></li>\r\n");
      out.write("                            <li><a href=\"./app-calender.html\">-월급 관리</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"fas fa-users\"></i><span class=\"nav-text\">인사</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("                            <li><a href=\"./chart-flot.html\">-공지사항</a></li>\r\n");
      out.write("                            <li><a href=\"./chart-morris.html\">-사원 등록 및 삭제</a></li>\r\n");
      out.write("                            <li><a href=\"./chart-chartjs.html\">-직급 관리</a></li>\r\n");
      out.write("                            <li><a href=\"./chart-chartist.html\">-휴가 및 출장 관리</a></li>\r\n");
      out.write("                            <li><a href=\"./chart-sparkline.html\">-출퇴근 정보</a></li>\r\n");
      out.write("                            <li><a href=\"./chart-peity.html\">-근태 점수</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"fas fa-calendar-alt\"></i><span class=\"nav-text\">일정</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("                            <li><a href=\"./index.html\">-일정상세보기</a></li>\r\n");
      out.write("                            <li><a href=\"./index.html\">-일정 등록</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"fas fa-user\"></i> <span class=\"nav-text\">마이 페이지</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("                            <li><a href=\"./email-inbox.html\">-개인정보 설정</a></li>\r\n");
      out.write("                            <li><a href=\"./email-read.html\">-출퇴근 현황</a></li>\r\n");
      out.write("                            <li><a href=\"./email-compose.html\">-근태점수</a></li>\r\n");
      out.write("                            <li><a href=\"./email-compose.html\">-연차</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"widgets.html\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"far fa-comments\"></i><span class=\"nav-text\">사내메신저</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Sidebar end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    <!--**********************************\r\n");
      out.write("        Scripts\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("    <script src=\"views/common/plugins/common/common.min.js\"></script>\r\n");
      out.write("    <script src=\"views/common/js/custom.min.js\"></script>\r\n");
      out.write("    <script src=\"views/common/js/settings.js\"></script>\r\n");
      out.write("    <script src=\"views/common/js/gleek.js\"></script>\r\n");
      out.write("    <script src=\"views/common/js/styleSwitcher.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Content body start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\t<div class=\"content-body\" style=\"background: white;\">\r\n");
      out.write("\t\t<div class=\"content-fluid\" style=\"height: 100px;\" align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<p style=\"font-size: 1.5em;\">출/퇴근</p>\r\n");
      out.write("\t\t\t\t<button class=\"col-sm-5 btn btn-outline-success\" style=\"height:50px;\">출근</button> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<button class=\"col-sm-5 btn btn-outline-danger\" style=\"height:50px;\">퇴근</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t<div class=\"content-fluid\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"./views/common/plugins/fullcalendar/css/fullcalendar.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- row -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>일정</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"card-box m-b-50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"calendar\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- end col -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- BEGIN MODAL -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal fade none-border\" id=\"event-modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<strong>일정추가</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-body\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default waves-effect\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-success save-event waves-effect waves-light\">Create\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tevent</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger delete-event waves-effect waves-light\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Delete</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Modal Add Category -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal fade none-border\" id=\"add-category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<strong>Add a category</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Category Name</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-white\" placeholder=\"Enter name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"category-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">종류</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control form-white\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-placeholder=\"Choose a color...\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"category-color\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"success\">Success</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"danger\">Danger</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"info\">Info</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"pink\">Pink</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"primary\">Primary</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"warning\">Warning</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default waves-effect\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-danger waves-effect waves-light save-category\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Save</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- END MODAL -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /# card -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /# column -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- #/ container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"./views/common/plugins/jqueryui/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<script src=\"./views/common/plugins/moment/moment.min.js\"></script>\r\n");
      out.write("\t<script src=\"./views/common/plugins/fullcalendar/js/fullcalendar.min.js\"></script>\r\n");
      out.write("\t<script src=\"./views/common/js/plugins-init/fullcalendar-init.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.container -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- #/ container -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--**********************************\r\n");
      out.write("            Content body end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--**********************************\r\n");
      out.write("            Footer start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                <p>Copyright &copy; Designed & Developed by <a href=\"https://themeforest.net/user/quixlab\">Quixlab</a> 2018</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Footer end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--**********************************\r\n");
      out.write("        Main wrapper end\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
