/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-19 17:38:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template.quixlab_002dmaster;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_002dblank_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n");
      out.write("    <title>Quixlab - Bootstrap Admin Dashboard Template by Themefisher.com</title>\n");
      out.write("    <!-- Favicon icon -->\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"images/favicon.png\">\n");
      out.write("    <!-- Custom Stylesheet -->\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!--*******************\n");
      out.write("        Preloader start\n");
      out.write("    ********************-->\n");
      out.write("    <div id=\"preloader\">\n");
      out.write("        <div class=\"loader\">\n");
      out.write("            <svg class=\"circular\" viewBox=\"25 25 50 50\">\n");
      out.write("                <circle class=\"path\" cx=\"50\" cy=\"50\" r=\"20\" fill=\"none\" stroke-width=\"3\" stroke-miterlimit=\"10\" />\n");
      out.write("            </svg>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!--*******************\n");
      out.write("        Preloader end\n");
      out.write("    ********************-->\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!--**********************************\n");
      out.write("        Main wrapper start\n");
      out.write("    ***********************************-->\n");
      out.write("    <div id=\"main-wrapper\">\n");
      out.write("\n");
      out.write("        <!--**********************************\n");
      out.write("            Nav header start\n");
      out.write("        ***********************************-->\n");
      out.write("        <div class=\"nav-header\">\n");
      out.write("            <div class=\"brand-logo\">\n");
      out.write("                <a href=\"index.html\">\n");
      out.write("                    <b class=\"logo-abbr\"><img src=\"images/logo.png\" alt=\"\"> </b>\n");
      out.write("                    <span class=\"logo-compact\"><img src=\"./images/logo-compact.png\" alt=\"\"></span>\n");
      out.write("                    <span class=\"brand-title\">\n");
      out.write("                        <img src=\"images/logo-text.png\" alt=\"\">\n");
      out.write("                    </span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--**********************************\n");
      out.write("            Nav header end\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("        <!--**********************************\n");
      out.write("            Header start\n");
      out.write("        ***********************************-->\n");
      out.write("        <div class=\"header\">    \n");
      out.write("            <div class=\"header-content clearfix\">\n");
      out.write("                \n");
      out.write("                <div class=\"nav-control\">\n");
      out.write("                    <div class=\"hamburger\">\n");
      out.write("                        <span class=\"toggle-icon\"><i class=\"icon-menu\"></i></span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"header-left\">\n");
      out.write("                    <div class=\"input-group icons\">\n");
      out.write("                        <div class=\"input-group-prepend\">\n");
      out.write("                            <span class=\"input-group-text bg-transparent border-0 pr-2 pr-sm-3\" id=\"basic-addon1\"><i class=\"mdi mdi-magnify\"></i></span>\n");
      out.write("                        </div>\n");
      out.write("                        <input type=\"search\" class=\"form-control\" placeholder=\"Search Dashboard\" aria-label=\"Search Dashboard\">\n");
      out.write("                        <div class=\"drop-down   d-md-none\">\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"header-right\">\n");
      out.write("                    <ul class=\"clearfix\">\n");
      out.write("                        <li class=\"icons dropdown\"><a href=\"javascript:void(0)\" data-toggle=\"dropdown\">\n");
      out.write("                                <i class=\"mdi mdi-email-outline\"></i>\n");
      out.write("                                <span class=\"badge gradient-1 badge-pill badge-primary\">3</span>\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"drop-down animated fadeIn dropdown-menu\">\n");
      out.write("                                <div class=\"dropdown-content-heading d-flex justify-content-between\">\n");
      out.write("                                    <span class=\"\">3 New Messages</span>  \n");
      out.write("                                    \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"dropdown-content-body\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li class=\"notification-unread\">\n");
      out.write("                                            <a href=\"javascript:void()\">\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"images/avatar/1.jpg\" alt=\"\">\n");
      out.write("                                                <div class=\"notification-content\">\n");
      out.write("                                                    <div class=\"notification-heading\">Saiful Islam</div>\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\n");
      out.write("                                                    <div class=\"notification-text\">Hi Teddy, Just wanted to let you ...</div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li class=\"notification-unread\">\n");
      out.write("                                            <a href=\"javascript:void()\">\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"images/avatar/2.jpg\" alt=\"\">\n");
      out.write("                                                <div class=\"notification-content\">\n");
      out.write("                                                    <div class=\"notification-heading\">Adam Smith</div>\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\n");
      out.write("                                                    <div class=\"notification-text\">Can you do me a favour?</div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"javascript:void()\">\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"images/avatar/3.jpg\" alt=\"\">\n");
      out.write("                                                <div class=\"notification-content\">\n");
      out.write("                                                    <div class=\"notification-heading\">Barak Obama</div>\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\n");
      out.write("                                                    <div class=\"notification-text\">Hi Teddy, Just wanted to let you ...</div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"javascript:void()\">\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"images/avatar/4.jpg\" alt=\"\">\n");
      out.write("                                                <div class=\"notification-content\">\n");
      out.write("                                                    <div class=\"notification-heading\">Hilari Clinton</div>\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\n");
      out.write("                                                    <div class=\"notification-text\">Hello</div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                    \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"icons dropdown\"><a href=\"javascript:void(0)\" data-toggle=\"dropdown\">\n");
      out.write("                                <i class=\"mdi mdi-bell-outline\"></i>\n");
      out.write("                                <span class=\"badge badge-pill gradient-2 badge-primary\">3</span>\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"drop-down animated fadeIn dropdown-menu dropdown-notfication\">\n");
      out.write("                                <div class=\"dropdown-content-heading d-flex justify-content-between\">\n");
      out.write("                                    <span class=\"\">2 New Notifications</span>  \n");
      out.write("                                    \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"dropdown-content-body\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"javascript:void()\">\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-success-lighten-2\"><i class=\"icon-present\"></i></span>\n");
      out.write("                                                <div class=\"notification-content\">\n");
      out.write("                                                    <h6 class=\"notification-heading\">Events near you</h6>\n");
      out.write("                                                    <span class=\"notification-text\">Within next 5 days</span> \n");
      out.write("                                                </div>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"javascript:void()\">\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-danger-lighten-2\"><i class=\"icon-present\"></i></span>\n");
      out.write("                                                <div class=\"notification-content\">\n");
      out.write("                                                    <h6 class=\"notification-heading\">Event Started</h6>\n");
      out.write("                                                    <span class=\"notification-text\">One hour ago</span> \n");
      out.write("                                                </div>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"javascript:void()\">\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-success-lighten-2\"><i class=\"icon-present\"></i></span>\n");
      out.write("                                                <div class=\"notification-content\">\n");
      out.write("                                                    <h6 class=\"notification-heading\">Event Ended Successfully</h6>\n");
      out.write("                                                    <span class=\"notification-text\">One hour ago</span>\n");
      out.write("                                                </div>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"javascript:void()\">\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-danger-lighten-2\"><i class=\"icon-present\"></i></span>\n");
      out.write("                                                <div class=\"notification-content\">\n");
      out.write("                                                    <h6 class=\"notification-heading\">Events to Join</h6>\n");
      out.write("                                                    <span class=\"notification-text\">After two days</span> \n");
      out.write("                                                </div>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                    \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"icons dropdown d-none d-md-flex\">\n");
      out.write("                            <a href=\"javascript:void(0)\" class=\"log-user\"  data-toggle=\"dropdown\">\n");
      out.write("                                <span>English</span>  <i class=\"fa fa-angle-down f-s-14\" aria-hidden=\"true\"></i>\n");
      out.write("                            </a>\n");
      out.write("                            <div class=\"drop-down dropdown-language animated fadeIn  dropdown-menu\">\n");
      out.write("                                <div class=\"dropdown-content-body\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li><a href=\"javascript:void()\">English</a></li>\n");
      out.write("                                        <li><a href=\"javascript:void()\">Dutch</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"icons dropdown\">\n");
      out.write("                            <div class=\"user-img c-pointer position-relative\"   data-toggle=\"dropdown\">\n");
      out.write("                                <span class=\"activity active\"></span>\n");
      out.write("                                <img src=\"images/user/1.png\" height=\"40\" width=\"40\" alt=\"\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"drop-down dropdown-profile   dropdown-menu\">\n");
      out.write("                                <div class=\"dropdown-content-body\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"app-profile.html\"><i class=\"icon-user\"></i> <span>Profile</span></a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"email-inbox.html\"><i class=\"icon-envelope-open\"></i> <span>Inbox</span> <div class=\"badge gradient-3 badge-pill badge-primary\">3</div></a>\n");
      out.write("                                        </li>\n");
      out.write("                                        \n");
      out.write("                                        <hr class=\"my-2\">\n");
      out.write("                                        <li>\n");
      out.write("                                            <a href=\"page-lock.html\"><i class=\"icon-lock\"></i> <span>Lock Screen</span></a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li><a href=\"page-login.html\"><i class=\"icon-key\"></i> <span>Logout</span></a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--**********************************\n");
      out.write("            Header end ti-comment-alt\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("        <!--**********************************\n");
      out.write("            Sidebar start\n");
      out.write("        ***********************************-->\n");
      out.write("        <div class=\"nk-sidebar\">           \n");
      out.write("            <div class=\"nk-nav-scroll\">\n");
      out.write("                <ul class=\"metismenu\" id=\"menu\">\n");
      out.write("                    <li class=\"nav-label\">Dashboard</li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-speedometer menu-icon\"></i><span class=\"nav-text\">Dashboard</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./index.html\">Home 1</a></li>\n");
      out.write("                            <!-- <li><a href=\"./index-2.html\">Home 2</a></li> -->\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"mega-menu mega-menu-sm\">\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-globe-alt menu-icon\"></i><span class=\"nav-text\">Layouts</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./layout-blank.html\">Blank</a></li>\n");
      out.write("                            <li><a href=\"./layout-one-column.html\">One Column</a></li>\n");
      out.write("                            <li><a href=\"./layout-two-column.html\">Two column</a></li>\n");
      out.write("                            <li><a href=\"./layout-compact-nav.html\">Compact Nav</a></li>\n");
      out.write("                            <li><a href=\"./layout-vertical.html\">Vertical</a></li>\n");
      out.write("                            <li><a href=\"./layout-horizontal.html\">Horizontal</a></li>\n");
      out.write("                            <li><a href=\"./layout-boxed.html\">Boxed</a></li>\n");
      out.write("                            <li><a href=\"./layout-wide.html\">Wide</a></li>\n");
      out.write("                            \n");
      out.write("                            \n");
      out.write("                            <li><a href=\"./layout-fixed-header.html\">Fixed Header</a></li>\n");
      out.write("                            <li><a href=\"layout-fixed-sidebar.html\">Fixed Sidebar</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-label\">Apps</li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-envelope menu-icon\"></i> <span class=\"nav-text\">Email</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./email-inbox.html\">Inbox</a></li>\n");
      out.write("                            <li><a href=\"./email-read.html\">Read</a></li>\n");
      out.write("                            <li><a href=\"./email-compose.html\">Compose</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-screen-tablet menu-icon\"></i><span class=\"nav-text\">Apps</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./app-profile.html\">Profile</a></li>\n");
      out.write("                            <li><a href=\"./app-calender.html\">Calender</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-graph menu-icon\"></i> <span class=\"nav-text\">Charts</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./chart-flot.html\">Flot</a></li>\n");
      out.write("                            <li><a href=\"./chart-morris.html\">Morris</a></li>\n");
      out.write("                            <li><a href=\"./chart-chartjs.html\">Chartjs</a></li>\n");
      out.write("                            <li><a href=\"./chart-chartist.html\">Chartist</a></li>\n");
      out.write("                            <li><a href=\"./chart-sparkline.html\">Sparkline</a></li>\n");
      out.write("                            <li><a href=\"./chart-peity.html\">Peity</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-label\">UI Components</li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-grid menu-icon\"></i><span class=\"nav-text\">UI Components</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./ui-accordion.html\">Accordion</a></li>\n");
      out.write("                            <li><a href=\"./ui-alert.html\">Alert</a></li>\n");
      out.write("                            <li><a href=\"./ui-badge.html\">Badge</a></li>\n");
      out.write("                            <li><a href=\"./ui-button.html\">Button</a></li>\n");
      out.write("                            <li><a href=\"./ui-button-group.html\">Button Group</a></li>\n");
      out.write("                            <li><a href=\"./ui-cards.html\">Cards</a></li>\n");
      out.write("                            <li><a href=\"./ui-carousel.html\">Carousel</a></li>\n");
      out.write("                            <li><a href=\"./ui-dropdown.html\">Dropdown</a></li>\n");
      out.write("                            <li><a href=\"./ui-list-group.html\">List Group</a></li>\n");
      out.write("                            <li><a href=\"./ui-media-object.html\">Media Object</a></li>\n");
      out.write("                            <li><a href=\"./ui-modal.html\">Modal</a></li>\n");
      out.write("                            <li><a href=\"./ui-pagination.html\">Pagination</a></li>\n");
      out.write("                            <li><a href=\"./ui-popover.html\">Popover</a></li>\n");
      out.write("                            <li><a href=\"./ui-progressbar.html\">Progressbar</a></li>\n");
      out.write("                            <li><a href=\"./ui-tab.html\">Tab</a></li>\n");
      out.write("                            <li><a href=\"./ui-typography.html\">Typography</a></li>\n");
      out.write("                        <!-- </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-layers menu-icon\"></i><span class=\"nav-text\">Components</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\"> -->\n");
      out.write("                            <li><a href=\"./uc-nestedable.html\">Nestedable</a></li>\n");
      out.write("                            <li><a href=\"./uc-noui-slider.html\">Noui Slider</a></li>\n");
      out.write("                            <li><a href=\"./uc-sweetalert.html\">Sweet Alert</a></li>\n");
      out.write("                            <li><a href=\"./uc-toastr.html\">Toastr</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"widgets.html\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-badge menu-icon\"></i><span class=\"nav-text\">Widget</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-label\">Forms</li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-note menu-icon\"></i><span class=\"nav-text\">Forms</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./form-basic.html\">Basic Form</a></li>\n");
      out.write("                            <li><a href=\"./form-validation.html\">Form Validation</a></li>\n");
      out.write("                            <li><a href=\"./form-step.html\">Step Form</a></li>\n");
      out.write("                            <li><a href=\"./form-editor.html\">Editor</a></li>\n");
      out.write("                            <li><a href=\"./form-picker.html\">Picker</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-label\">Table</li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-menu menu-icon\"></i><span class=\"nav-text\">Table</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./table-basic.html\" aria-expanded=\"false\">Basic Table</a></li>\n");
      out.write("                            <li><a href=\"./table-datatable.html\" aria-expanded=\"false\">Data Table</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-label\">Pages</li>\n");
      out.write("                    <li>\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\n");
      out.write("                            <i class=\"icon-notebook menu-icon\"></i><span class=\"nav-text\">Pages</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul aria-expanded=\"false\">\n");
      out.write("                            <li><a href=\"./page-login.html\">Login</a></li>\n");
      out.write("                            <li><a href=\"./page-register.html\">Register</a></li>\n");
      out.write("                            <li><a href=\"./page-lock.html\">Lock Screen</a></li>\n");
      out.write("                            <li><a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">Error</a>\n");
      out.write("                                <ul aria-expanded=\"false\">\n");
      out.write("                                    <li><a href=\"./page-error-404.html\">Error 404</a></li>\n");
      out.write("                                    <li><a href=\"./page-error-403.html\">Error 403</a></li>\n");
      out.write("                                    <li><a href=\"./page-error-400.html\">Error 400</a></li>\n");
      out.write("                                    <li><a href=\"./page-error-500.html\">Error 500</a></li>\n");
      out.write("                                    <li><a href=\"./page-error-503.html\">Error 503</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--**********************************\n");
      out.write("            Sidebar end\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("        <!--**********************************\n");
      out.write("            Content body start\n");
      out.write("        ***********************************-->\n");
      out.write("        <div class=\"content-body\">\n");
      out.write("\n");
      out.write("            <div class=\"row page-titles mx-0\">\n");
      out.write("                <div class=\"col p-md-0\">\n");
      out.write("                    <ol class=\"breadcrumb\">\n");
      out.write("                        <li class=\"breadcrumb-item\"><a href=\"javascript:void(0)\">Dashboard</a></li>\n");
      out.write("                        <li class=\"breadcrumb-item active\"><a href=\"javascript:void(0)\">Home</a></li>\n");
      out.write("                    </ol>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- row -->\n");
      out.write("\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <!-- #/ container -->\n");
      out.write("        </div>\n");
      out.write("        <!--**********************************\n");
      out.write("            Content body end\n");
      out.write("        ***********************************-->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!--**********************************\n");
      out.write("            Footer start\n");
      out.write("        ***********************************-->\n");
      out.write("        <div class=\"footer\">\n");
      out.write("            <div class=\"copyright\">\n");
      out.write("                <p>Copyright &copy; Designed & Developed by <a href=\"https://themeforest.net/user/quixlab\">Quixlab</a> 2018</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--**********************************\n");
      out.write("            Footer end\n");
      out.write("        ***********************************-->\n");
      out.write("    </div>\n");
      out.write("    <!--**********************************\n");
      out.write("        Main wrapper end\n");
      out.write("    ***********************************-->\n");
      out.write("\n");
      out.write("    <!--**********************************\n");
      out.write("        Scripts\n");
      out.write("    ***********************************-->\n");
      out.write("    <script src=\"plugins/common/common.min.js\"></script>\n");
      out.write("    <script src=\"js/custom.min.js\"></script>\n");
      out.write("    <script src=\"js/settings.js\"></script>\n");
      out.write("    <script src=\"js/gleek.js\"></script>\n");
      out.write("    <script src=\"js/styleSwitcher.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
